TEXTS = {
    'welcome': "[bold cyan]Добро пожаловать в сборщик данных FunPay[/bold cyan]",
    'url_input': "[bold #10e8a0]Введите URL страницы продаж (или нажмите Enter для дефолтного '{}'): [/bold #10e8a0]",
    'cookie_warn': "[bold red]ВНИМАНИЕ: для сбора данных нужны ваши Cookie[/bold red]",
    'cookie_choice': "[bold cyan]Выберите способ:\n1. Автосбор (из браузера)\n2. Ввести вручную[/bold cyan]",
    'enter_choice': "[bold #10e8a0]Введите ваш выбор (1 или 2): [/bold #10e8a0]",
    'manual': "[bold #cf8021]Как получить?: F12 -> Network -> F5 -> найти funpay.com -> Copy as cURL -> скопировать 'Cookie: '[/bold #cf8021]",
    'enter_cookie': "[bold #10e8a0]Вставьте ваши Cookie: [/bold #10e8a0]",
    'wrong_choice': "[bold red]Неверный выбор. Отключение.[/bold red]",
    'fatal_cookie': "[bold red]Критическая ошибка: вы не ввели Cookie. Отключение.[/bold red]",
    'connecting': "[bold cyan]Пытаемся подключиться к FunPay...[/bold cyan]",
    'success': "[bold #21cf44]Успешное подключение[/bold #21cf44]",
    'found': "[bold yellow]Найдено продаж: {}[/bold yellow]",
    'collected': "[bold cyan]Собранные данные:[/bold cyan]",
    'save_choice': "[bold #10e8a0]Сохранить данные в csv-файл? Введите y/д - если да, или любой другой символ - если нет: [/bold #10e8a0]",
    'found_old_file': "[bold white]Найден старый файл с {} записями. Обновляю, подождите...[/bold white]",
    'success_update': "[bold #21cf44]Успешное обновление! Добавлено {} новых записей[/bold #21cf44]",
    'total_notes': "[bold white]Всего записей в файле: {}[/bold white]",
    'saved': "[bold #21cf44]Успешно создан csv-файл с данными[/bold #21cf44]",
    'success_no_save': "[bold #21cf44]Успешно[/bold #21cf44]",
    'error_conn': "[bold red]Ошибка подключения. Код статуса: {}[/bold red]",
    'revenue_visual': "Выручка по месяцам {}",
    'run_analytics': "[bold white]Запустить текстовую аналитику? (y/n): [/bold white]",
    'run_charts': "[bold white]Построить графики? (y/n): [/bold white]",
    'load_data': "[bold #21cf44]Загружаем данные из my_sales.csv[/bold #21cf44]",
    'rec_upload': "\n[bold cyan]Загружено записей: {}[bold cyan]",
    'fin_sum': "\n[bold red]ФИНАНСОВАЯ СВОДКА:[bold red]",
    'gen_stat': "\n[bold #21cf44]Общая статистика:[bold #21cf44]",
    'total_deals': "[bold white]Общее количество сделок: {}[bold white]",
    'total_rev': "[bold white]Общая выручка: {} {}[bold white]",
    'avg_check': "[bold white]Средний чек: {} {}[bold white]",
    'closed_deals': "\n[bold #21cf44]Закрытые сделки:[bold #21cf44]",
    'count': "[bold white]Количество: {}[bold white]",
    'sum': "[bold white]Сумма: {} {}[bold white]",
    'refunds': "\n[bold red]Возвраты:[bold red]",
    'ref_count': "[bold white]Количество возвратов: {}[bold white]",
    'ref_sum': "[bold white]Сумма возвратов: {} {}[bold white]",
    'ref_percent': "[bold white]Процент возвратов: {}%[bold white]",
    'date_analyzer': "[bold #21cf44]Аналитика по датам:[bold #21cf44]",
    'an_data_notes': "[bold white]Проанализированно {} из {} записей[bold white]",
    'sls_by_month': "\n[bold #21cf44]Продажи по месяцам:[bold #21cf44]",
    'sls_week': "\n[bold #21cf44]Продажи по дням недели:[bold #21cf44]",
    'prof_error': "[bold red]Ошибка подключения к профилю. Код ошибки: {}[bold red]",
    'rev_title': "[bold cyan]Аналитика рейтинга и отзывов:[bold cyan]",
    'green_rating': "[bold green]Рейтинг: {}[bold green]",
    'yellow_rating': "[bold yellow]Рейтинг: {}[bold yellow]",
    'red_rating': "[bold red]Рейтинг: {}[bold red]",
    'rev_searched': "[bold yellow]Отзывов проверено: {}[bold yellow]",
    'top_rev_cnt': "\n[bold cyan]Топ ключевых слов в отзывах:[/bold cyan]",
    'rev_results': "[bold white]Слово[bold white] [{}]{}[{}] [bold white]встречается[bold white] [bold cyan]{}[bold cyan] [bold white]раз[bold white]",
    'rev_error': "[bold red]Ошибка поиска отзывов[bold red]",
    'run_reviews': "[bold white]Запустить аналитику отзывов? (y/n): [bold white]",
    'enter_prof_url': "[bold red]ВНИМАНИЕ! Перед запуском аналитики отзывов введите ссылку на Ваш профиль FunPay: [bold red]",
    'good_words': ["быстро", "хорошо", "спасибо", "рекомендую", "отлично", "топ", "качественно", "адекватно", "+rep"],
    'bad_words': ["обман", "плохо", "долго", "бан", "кидалово", "мошенник", "кинуло", "обманул", "-rep", "откинуло", "забанило", "забанили"]
}