TEXTS = {
    'welcome': "[bold cyan]Welcome to FunPay data collector[/bold cyan]",
    'url_input': "[bold #10e8a0]Enter your sales-page URL (or only push Enter to set default URL: '{}'): [/bold #10e8a0]",
    'cookie_warn': "[bold red]WARNING: to collect your data you must enter your cookies[/bold red]",
    'cookie_choice': "[bold cyan]You can choose:\n1. Collect your cookies in auto-mode\n2. Enter your cookies manually[/bold cyan]",
    'enter_choice': "[bold #10e8a0]Enter 1 for auto-mode or 2 for enter your cookies manually: [/bold #10e8a0]",
    'manual': "[bold #cf8021]How?: F12 -> Network -> F5 -> find: funpay.com - trade.html (right click) -> Copy as cURL -> Copy your Cookie: [/bold #cf8021]",
    'enter_cookie': "[bold #10e8a0]Enter your cookies: [/bold #10e8a0]",
    'wrong_choice': "[bold red]Incorrect choice. Disconnecting.[/bold red]",
    'fatal_cookie': "[bold red]Fatal error: you aren't enter your cookies. Disconnecting.[/bold red]",
    'connecting': "[bold cyan]Try to connect to FunPay...[/bold cyan]",
    'success': "[bold #21cf44]Succesful connection[/bold #21cf44]",
    'found': "[bold yellow]Found {} sales[/bold yellow]",
    'collected': "[bold cyan]Collected data: [/bold cyan]",
    'save_choice': "[bold #10e8a0]Do you want to save data to csv-file? Enter y/н - if yes or other symbol - if no: [/bold #10e8a0]",
    'found_old_file': "[bold white]Found data-file with {} data-notes. Updating, please wait[/bold white]",
    'success_update': "[bold #21cf44]Succesful updating! Add {} new notes[/bold #21cf44]",
    'total_notes': "[bold #10e8a0]Notes in new data-file: {}[/bold #10e8a0]",
    'saved': "[bold #21cf44]Succesful create csv-data file[/bold #21cf44]",
    'success_no_save': "[bold #21cf44]Succesfully[/bold #21cf44]",
    'error_conn': "[bold red]Connection error. Status code: {}[/bold red]",
    'revenue_visual': "Revenue by month {}",
    'run_analytics': "[bold white]Run text analytics? (y/n): [/bold white]",
    'run_charts': "[bold white]Build charts? (y/n): [/bold white]",
    'load_data': "[bold #21cf44]Loading data from my_sales.csv[/bold #21cf44]",
    'rec_upload': "\n[bold cyan]Records uploaded: {}[bold cyan]",
    'fin_sum': "\n[bold red]FINANCIAL SUMMARY:[bold red]",
    'gen_stat': "\n[bold #21cf44]General statistics:[bold #21cf44]",
    'total_deals': "[bold white]Total deals: {}[bold white]",
    'total_rev': "[bold white]Total revenue: {} {}[bold white]",
    'avg_check': "[bold white]Average check: {} {}[bold white]",
    'closed_deals': "\n[bold #21cf44]Closed deals:[bold #21cf44]",
    'count': "[bold white]Count: {}[bold white]",
    'sum': "[bold white]Sum: {} {}[bold white]",
    'refunds': "\n[bold red]Refunds:[bold red]",
    'ref_count': "[bold white]Count: {}[bold white]",
    'ref_sum': "[bold white]Sum: {} {}[bold white]",
    'ref_percent': "[bold white]Return percentage: {}%[bold white]",
    'date_analyzer': "[bold #21cf44]Date analyzer:[bold #21cf44]",
    'an_data_notes': "[bold white]Analyzed {} of {} data-notes[bold white]",
    'sls_by_month': "\n[bold #21cf44]Sales by month:[bold #21cf44]",
    'sls_week': "\n[bold #21cf44]Sales by day of the week:[bold #21cf44]",
    'prof_error': "[bold red]Error connecting to profile. Error code: {}[bold red]",
    'rev_title': "[bold cyan]Analytical rating and reviews:[bold cyan]",
    'rating': "[bold bright_green]Rating: {}[bold bright_green]",
    'rev_searched': "[bold yellow]Reviews verified: {}[bold yellow]",
    'rev_error': "[bold red]Error searching for reviews: {}[bold red]"
}